# Generated by Django 4.1 on 2023-01-04 15:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0002_initial'),
        ('photos', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='sale',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='sales.sales'),
        ),
    ]
