# Generated by Django 4.1 on 2023-01-09 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0003_alter_board_author_alter_comment_article_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='board',
            name='view',
            field=models.IntegerField(default=0),
        ),
    ]
