# Generated by Django 4.1 on 2023-01-10 11:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0004_board_view'),
    ]

    operations = [
        migrations.RenameField(
            model_name='board',
            old_name='view',
            new_name='views',
        ),
    ]
