# Generated by Django 4.1 on 2023-01-06 09:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0003_alter_answer_author_alter_answer_post_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='ask_comment',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='sales.question'),
        ),
        migrations.DeleteModel(
            name='Answer',
        ),
    ]
